export const models = [
  {
    carId: "bmw-1-series-m-coupe",
    carName: "1 Series M Coupé",
    subTitle: "The Ultimate Compact M Performance Machine",
    image: "assets/models/1 model/1-series-m135i.png",
    description:
      "The BMW 1 Series M Coupé is a rare, high-performance compact sports car that combines the agility of the 1 Series chassis with M Division engineering. Powered by a turbocharged inline-six engine, it delivers exhilarating performance and precise handling, making it a modern classic among driving enthusiasts.",
    price: 50000,
    performance: {
      horsepower: 340,
      torque: 332,
      acceleration: 4.9,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "3.0L twin-turbocharged inline-6 (N54)",
      transmission: "6-speed manual",
      fuelEconomy: "13.6 L/100 km city / 7.3 L/100 km highway",
      weight: 1495,
    },
    dimensions: {
      length: 4380,
      width: 1803,
      height: 1420,
      wheelbase: 2660,
    },
    features: {
      driveType: "Rear-Wheel Drive (RWD)",
      tireSize: {
        front: "245/35 R19",
        rear: "265/35 R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 53,
    },
  },
  {
    carId: "bmw-128ti",
    carName: "128ti",
    subTitle: "The Front-Wheel-Drive Hot Hatch",
    image: "assets/models/1 model/1-series.png",
    description:
      "The BMW 1 Series 128ti is a sporty hatchback that offers dynamic driving performance with its turbocharged engine and front-wheel-drive layout. Positioned between the standard 1 Series models and the M135i xDrive, the 128ti provides a balance of everyday usability and spirited driving.",
    price: 40000,
    performance: {
      horsepower: 241,
      torque: 280,
      acceleration: 6.3,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "2.0L turbocharged inline-4",
      transmission: "8-speed Sport Steptronic automatic",
      fuelEconomy: "6.8 L/100 km combined",
      weight: 1520,
    },
    dimensions: {
      length: 4319,
      width: 1799,
      height: 1434,
      wheelbase: 2670,
    },
    features: {
      driveType: "Front-Wheel Drive (FWD)",
      tireSize: {
        front: "225/40 R18",
        rear: "245/35 R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 50,
    },
  },
  {
    carId: "bmw-2-series-coupe",
    carName: "2 Series Coupé",
    subTitle: "The Compact Rear-Wheel-Drive Sports Coupé",
    image: "assets/models/2 model/2-series.png",
    description:
      "The BMW 2 Series Coupé combines classic rear-wheel-drive dynamics with modern design and technology. It's designed for driving enthusiasts seeking agility and performance in a compact package.",
    price: 36000,
    performance: {
      horsepower: 374,
      torque: 369,
      acceleration: 4.3,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "3.0L 6-cylinder turbocharged",
      transmission: "8-speed automatic transmission",
      fuelEconomy: "6.4 to 8.8 L/100 km",
      weight: 1490,
    },
    dimensions: {
      length: 4537,
      width: 1838,
      height: 1390,
      wheelbase: 2741,
    },
    features: {
      driveType: "Rear-Wheel Drive (RWD)",
      tireSize: {
        front: "225/45 R18",
        rear: "255/40 R18",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 52,
    },
  },
  {
    carId: "bmw-2-series-gran-coupe",
    carName: "2 Series Gran Coupé",
    subTitle: "The Sporty Four-Door Coupé",
    image: "assets/models/2 model/M2-Gran.png",
    description:
      "The BMW 2 Series Gran Coupé offers a blend of dynamic performance and elegant design in a four-door coupé format. It's equipped with advanced technology and efficient engines, making it suitable for both city driving and long journeys.",
    price: 35000,
    performance: {
      horsepower: 306,
      torque: 332,
      acceleration: 4.9,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "2.0L 4-cylinder turbocharged",
      transmission: "8-speed automatic",
      fuelEconomy: "4.6 to 7.8 L/100 km",
      weight: 1350,
    },
    dimensions: {
      length: 4526,
      width: 1800,
      height: 1420,
      wheelbase: 2670,
    },
    features: {
      driveType: "Front-Wheel Drive (FWD)",
      tireSize: {
        front: "225/45 R17",
        rear: "245/40 R17",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 50,
    },
  },
  {
    carId: "bmw-m2-coupe",
    carName: "M2 Coupé",
    subTitle: "The High-Performance Compact Sports Car",
    image: "assets/models/2 model/m2.png",
    description:
      "The BMW M2 Coupé delivers exhilarating performance with its powerful engine and precise handling. It's designed for driving enthusiasts seeking a compact car with track-capable dynamics.",
    price: 62000,
    performance: {
      horsepower: 460,
      torque: 406,
      acceleration: 3.9,
      topSpeed: 285,
    },
    powerTrain: {
      engine: "3.0L twin-turbocharged inline-6 (S58)",
      transmission: "8-speed M Steptronic automatic",
      fuelEconomy: "10.2–10.3 L/100 km",
      weight: 1725,
    },
    dimensions: {
      length: 4580,
      width: 1887,
      height: 1403,
      wheelbase: 2747,
    },
    features: {
      driveType: "Rear-Wheel Drive (RWD)",
      tireSize: {
        front: "275/35 ZR19",
        rear: "285/30 ZR20",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 52,
    },
  },
  {
    carId: "bmw-330i",
    carName: "330i",
    subTitle: "Sporty Elegance",
    image: "assets/models/3 model/M340i.webp",
    description:
      "The 330i combines dynamic performance with everyday practicality, featuring a turbocharged 2.0-liter engine and a refined interior.",
    price: 41450,
    performance: {
      horsepower: 255,
      torque: 295,
      acceleration: 5.6,
      topSpeed: 210,
    },
    powerTrain: {
      engine: "2.0L Turbocharged Inline-4",
      transmission: "8-speed automatic",
      fuelEconomy: "25 MPG city / 34 MPG highway",
      weight: 3589,
    },
    dimensions: {
      length: 4710,
      width: 1827,
      height: 1435,
      wheelbase: 2860,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "225/45R18",
        rear: "225/45R18",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-320i",
    carName: "320i",
    subTitle: "Efficient Luxury",
    image: "assets/models/3 model/M330i.webp",
    description:
      "The 320i offers a balance of efficiency and luxury, equipped with a 2.0-liter engine and premium features.",
    price: 41450,
    performance: {
      horsepower: 184,
      torque: 221,
      acceleration: 7.7,
      topSpeed: 230,
    },
    powerTrain: {
      engine: "2.0L Inline-4",
      transmission: "8-speed automatic",
      fuelEconomy: "Not specified",
      weight: 1580,
    },
    dimensions: {
      length: 4710,
      width: 1827,
      height: 1435,
      wheelbase: 2860,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R18",
        rear: "225/45R18",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 59,
    },
  },
  {
    carId: "bmw-m3",
    carName: "M3",
    subTitle: "Ultimate Performance",
    image: "assets/models/3 model/m3.webp",
    description:
      "The M3 delivers track-ready performance with a twin-turbocharged engine and aggressive styling.",
    price: 71800,
    performance: {
      horsepower: 503,
      torque: 479,
      acceleration: 3.4,
      topSpeed: 302,
    },
    powerTrain: {
      engine: "3.0L Twin-Turbocharged Inline-6",
      transmission: "8-speed automatic",
      fuelEconomy: "Not specified",
      weight: 0,
    },
    dimensions: {
      length: 4900,
      width: 1900,
      height: 1440,
      wheelbase: 2850,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "275/35 ZR19",
        rear: "285/30 ZR20",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-430i-coupe",
    carName: "430i Coupé",
    subTitle: "Elegant Performance Coupe",
    image: "assets/models/4 model/M430i.webp",
    description:
      "The 430i Coupe combines sleek design with dynamic performance, featuring a turbocharged engine and rear-wheel drive.",
    price: 47400,
    performance: {
      horsepower: 255,
      torque: 295,
      acceleration: 5.5,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "2.0L Turbocharged Inline-4",
      transmission: "8-speed automatic",
      fuelEconomy: "25 MPG city / 34 MPG highway",
      weight: 3578,
    },
    dimensions: {
      length: 4779,
      width: 1850,
      height: 1380,
      wheelbase: 2850,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "225/45R18",
        rear: "225/45R18",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-430i-gran-coupe",
    carName: "430i Gran Coupé",
    subTitle: "Sporty Elegance in a Four-Door",
    image: "assets/models/4 model/M430i-Gran.webp",
    description:
      "The 430i xDrive Gran Coupe offers the practicality of four doors with the performance of a coupe, featuring all-wheel drive and a turbocharged engine.",
    price: 45900,
    performance: {
      horsepower: 255,
      torque: 295,
      acceleration: 5.8,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "2.0L Turbocharged Inline-4",
      transmission: "8-speed automatic",
      fuelEconomy: "25 MPG city / 34 MPG highway",
      weight: 3792,
    },
    dimensions: {
      length: 4795,
      width: 1860,
      height: 1440,
      wheelbase: 2850,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R18",
        rear: "225/45R18",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-m4-coupe",
    carName: "M4 Coupé",
    subTitle: "Track-Ready Performance",
    image: "assets/models/4 model/m4.webp",
    description:
      "The M4 delivers exhilarating performance with a twin-turbocharged inline-six engine, aggressive styling, and rear-wheel drive.",
    price: 74700,
    performance: {
      horsepower: 473,
      torque: 406,
      acceleration: 3.8,
      topSpeed: 290,
    },
    powerTrain: {
      engine: "3.0L Twin-Turbocharged Inline-6",
      transmission: "6-speed manual",
      fuelEconomy: "16 MPG city / 23 MPG highway",
      weight: 3830,
    },
    dimensions: {
      length: 4800,
      width: 1900,
      height: 1390,
      wheelbase: 2850,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "275/35 ZR19",
        rear: "285/30 ZR20",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-530i",
    carName: "530i",
    subTitle: "Luxury and Performance",
    image: "assets/models/5 model/M530i.webp",
    description:
      "The 530i offers a blend of luxury and performance, featuring a turbocharged 2.0-liter engine and advanced technology.",
    price: 54800,
    performance: {
      horsepower: 248,
      torque: 258,
      acceleration: 5.9,
      topSpeed: 210,
    },
    powerTrain: {
      engine: "2.0L Turbocharged Inline-4",
      transmission: "8-speed automatic",
      fuelEconomy: "25 MPG city / 33 MPG highway",
      weight: 3783,
    },
    dimensions: {
      length: 4978,
      width: 1864,
      height: 1478,
      wheelbase: 2978,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "225/55R17",
        rear: "225/55R17",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 18.0,
    },
  },
  {
    carId: "bmw-m5",
    carName: "M5",
    subTitle: "Ultimate Performance Sedan",
    image: "assets/models/5 model/M5.webp",
    description:
      "The M5 delivers exceptional performance with a twin-turbocharged V8 engine and advanced handling capabilities.",
    price: 109900,
    performance: {
      horsepower: 617,
      torque: 553,
      acceleration: 3.1,
      topSpeed: 305,
    },
    powerTrain: {
      engine: "4.4L Twin-Turbocharged V8",
      transmission: "8-speed automatic",
      fuelEconomy: "15 MPG city / 21 MPG highway",
      weight: 4370,
    },
    dimensions: {
      length: 5044,
      width: 1904,
      height: 1457,
      wheelbase: 2982,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "275/35R20",
        rear: "285/35R21",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 21.1,
    },
  },
  {
    carId: "bmw-630i-gt",
    carName: "630i Gran Turismo",
    subTitle: "Luxury and Performance",
    image: "assets/models/6 model/BMW 6 Series Gran Turismo.png",
    description:
      "The 630i M Sport offers a blend of luxury and performance, featuring a turbocharged 2.0-liter engine and advanced technology.",
    price: 88000,
    performance: {
      horsepower: 258,
      torque: 295,
      acceleration: 6.5,
      topSpeed: 0,
    },
    powerTrain: {
      engine: "2.0L Turbocharged Inline-4",
      transmission: "8-speed Steptronic Sport Automatic",
      fuelEconomy: "Approximately 13.3 km/L",
      weight: 0,
    },
    dimensions: {
      length: 0,
      width: 0,
      height: 0,
      wheelbase: 0,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "225/45R17",
        rear: "225/45R17",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-740i",
    carName: "740i",
    subTitle: "Luxury Performance Sedan",
    image: "assets/models/7 model/740i.webp",
    description:
      "The 740i offers a blend of luxury and performance, featuring a turbocharged 3.0-liter inline-six engine and advanced technology.",
    price: 95700,
    performance: {
      horsepower: 375,
      torque: 331,
      acceleration: 5.2,
      topSpeed: 210,
    },
    powerTrain: {
      engine: "3.0L Inline-6 TwinPower Turbo",
      transmission: "8-speed automatic",
      fuelEconomy: "25 MPG city / 31 MPG highway",
      weight: 4720,
    },
    dimensions: {
      length: 5390,
      width: 1950,
      height: 1544,
      wheelbase: 0,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "255/45R20",
        rear: "285/40R20",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 19.5,
    },
  },
  {
    carId: "bmw-i7-xdrive60",
    carName: "i7 xDrive60",
    subTitle: "All-Electric Luxury Sedan",
    image: "assets/models/7 model/760i.webp",
    description:
      "The i7 xDrive60 combines electric performance with luxury, featuring dual electric motors and a high-capacity battery.",
    price: 119300,
    performance: {
      horsepower: 536,
      torque: 549,
      acceleration: 4.7,
      topSpeed: 240,
    },
    powerTrain: {
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "81 MPGe city / 85 MPGe highway",
      weight: 5917,
    },
    dimensions: {
      length: 5391,
      width: 1950,
      height: 1544,
      wheelbase: 3215,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "255/45R20",
        rear: "285/40R20",
      },
      battery: "105.7 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-8-series-convertible",
    carName: "8 Series Convertible",
    subTitle: "Luxury Open-Air Performance",
    image: "assets/models/8 model/M8.webp",
    description:
      "The 2023 BMW 8 Series Convertible combines elegant design with powerful performance, offering a premium open-air driving experience.",
    price: 97100,
    performance: {
      horsepower: 335,
      torque: 368,
      acceleration: 5.2,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "3.0L Inline-6 TwinPower Turbo",
      transmission: "8-speed automatic",
      fuelEconomy: "21 MPG city / 29 MPG highway",
      weight: 4262,
    },
    dimensions: {
      length: 5080,
      width: 1900,
      height: 1370,
      wheelbase: 2820,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "245/40R19",
        rear: "275/35R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 18.0,
    },
  },
  {
    carId: "bmw-840i-coupe",
    carName: "840i Coupé",
    subTitle: "Luxury Performance Coupe",
    image: "assets/models/8 model/M840i.webp",
    description:
      "The 840i Coupe offers a harmonious blend of luxury and performance, featuring a turbocharged inline-six engine, rear-wheel drive, and a host of premium features.",
    price: 87500,
    performance: {
      horsepower: 335,
      torque: 368,
      acceleration: 5.2,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "3.0L Inline-6 TwinPower Turbo",
      transmission: "8-speed automatic",
      fuelEconomy: "22 MPG city / 29 MPG highway",
      weight: 4262,
    },
    dimensions: {
      length: 5080,
      width: 1900,
      height: 1370,
      wheelbase: 2820,
    },
    features: {
      driveType: "Rear-Wheel Drive",
      tireSize: {
        front: "245/40R19",
        rear: "275/35R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 18.0,
    },
  },
  {
    carId: "bmw-i4",
    carName: "i4",
    subTitle: "Electric Gran Coupe",
    image: "assets/models/I model/i4.webp",
    description:
      "The i4 combines the elegance of a coupe with the performance of an M model, offering an engaging driving experience with zero emissions.",
    price: 52000,
    performance: {
      horsepower: 536,
      torque: 317,
      acceleration: 3.9,
      topSpeed: 225,
    },
    powerTrain: {
      engine: "Electric Motor",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "Not specified",
      weight: 2125,
    },
    dimensions: {
      length: 4783,
      width: 1852,
      height: 1448,
      wheelbase: 2856,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R17",
        rear: "225/45R17",
      },
      battery: "83.9 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-i5",
    carName: "i5",
    subTitle: "Electric Executive Sedan",
    image: "assets/models/I model/i5.webp",
    description:
      "The i5 offers a blend of luxury and performance, featuring advanced technology and a spacious interior.",
    price: 67795,
    performance: {
      horsepower: 590,
      torque: 442,
      acceleration: 3.8,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "Not specified",
      weight: 2300,
    },
    dimensions: {
      length: 5060,
      width: 1900,
      height: 1515,
      wheelbase: 2995,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R17",
        rear: "225/45R17",
      },
      battery: "81.2 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-i7",
    carName: "i7",
    subTitle: "Electric Luxury Sedan",
    image: "assets/models/I model/i7.webp",
    description:
      "The i7 combines luxury with electric performance, offering a serene driving experience with advanced technology.",
    price: 119300,
    performance: {
      horsepower: 536,
      torque: 553,
      acceleration: 4.7,
      topSpeed: 240,
    },
    powerTrain: {
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "Not specified",
      weight: 2680,
    },
    dimensions: {
      length: 5391,
      width: 1950,
      height: 1544,
      wheelbase: 3215,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "255/45R20",
        rear: "285/40R20",
      },
      battery: "105.7 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-ix",
    carName: "iX",
    subTitle: "Electric SUV",
    image: "assets/models/I model/iX.webp",
    description:
      "The iX offers a spacious interior and advanced technology, combining the practicality of an SUV with electric performance.",
    price: 84100,
    performance: {
      horsepower: 516,
      torque: 564,
      acceleration: 4.6,
      topSpeed: 200,
    },
    powerTrain: {
      engine: "Dual Electric Motors",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "Not specified",
      weight: 2535,
    },
    dimensions: {
      length: 4953,
      width: 1995,
      height: 1695,
      wheelbase: 2995,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R17",
        rear: "225/45R17",
      },
      battery: "105.2 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-ix2",
    carName: "iX2",
    subTitle: "Electric Compact SUV",
    image: "assets/models/I model/iX2.webp",
    description:
      "The iX2 combines the compact size of the X2 with electric performance, offering a stylish and efficient driving experience.",
    price: 53000,
    performance: {
      horsepower: 313,
      torque: 364,
      acceleration: 6.6,
      topSpeed: 180,
    },
    powerTrain: {
      engine: "Electric Motor",
      transmission: "Single-Speed Automatic",
      fuelEconomy: "Not specified",
      weight: 2000,
    },
    dimensions: {
      length: 4360,
      width: 1825,
      height: 1620,
      wheelbase: 2690,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "225/45R17",
        rear: "225/45R17",
      },
      battery: "66.5 kWh",
      fuelTank: 0,
    },
  },
  {
    carId: "bmw-x3",
    carName: "X3",
    subTitle: "Compact Luxury SUV",
    image: "assets/models/X model/X3.webp",
    description:
      "The 2023 BMW X3 offers a blend of performance, comfort, and utility, featuring a range of powerful engines and advanced technology.",
    price: 46200,
    performance: {
      horsepower: 248,
      torque: 258,
      acceleration: 6.0,
      topSpeed: 209,
    },
    powerTrain: {
      engine: "2.0L Inline-4 Turbocharged",
      transmission: "8-speed automatic",
      fuelEconomy: "21 MPG city / 28 MPG highway",
      weight: 4079,
    },
    dimensions: {
      length: 4730,
      width: 1890,
      height: 1670,
      wheelbase: 2860,
    },
    features: {
      driveType: "Rear-Wheel Drive (sDrive30i)",
      tireSize: {
        front: "245/50R19",
        rear: "245/50R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-x4",
    carName: "X4",
    subTitle: "Sporty Compact SUV",
    image: "assets/models/X model/X4.webp",
    description:
      "The 2023 BMW X4 combines the practicality of an SUV with the performance of a sports coupe, offering dynamic handling and a stylish design.",
    price: 54200,
    performance: {
      horsepower: 248,
      torque: 258,
      acceleration: 6.0,
      topSpeed: 209,
    },
    powerTrain: {
      engine: "2.0L Inline-4 Turbocharged",
      transmission: "8-speed automatic",
      fuelEconomy: "21 MPG city / 28 MPG highway",
      weight: 3210,
    },
    dimensions: {
      length: 4770,
      width: 1910,
      height: 1620,
      wheelbase: 2855,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "245/50R19",
        rear: "245/50R19",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 15.6,
    },
  },
  {
    carId: "bmw-x5",
    carName: "X5",
    subTitle: "Luxury Midsize SUV",
    image: "assets/models/X model/X5.webp",
    description:
      "The 2023 BMW X5 offers a luxurious interior, advanced technology, and powerful engine options, making it a versatile choice for those seeking performance and comfort.",
    price: 61600,
    performance: {
      horsepower: 335,
      torque: 331,
      acceleration: 5.3,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "3.0L Inline-6 Turbocharged",
      transmission: "8-speed automatic",
      fuelEconomy: "21 MPG city / 26 MPG highway",
      weight: 4828,
    },
    dimensions: {
      length: 4920,
      width: 1980,
      height: 1745,
      wheelbase: 2975,
    },
    features: {
      driveType: "Rear-Wheel Drive (sDrive40i)",
      tireSize: {
        front: "275/45R20",
        rear: "305/40R20",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 21.9,
    },
  },
  {
    carId: "bmw-x5-m",
    carName: "X5 M",
    subTitle: "High-Performance Luxury SUV",
    image: "assets/models/X model/X5M.webp",
    description:
      "The 2023 BMW X5 M combines the versatility of an SUV with the performance of a sports car, featuring a powerful engine and advanced technology.",
    price: 108900,
    performance: {
      horsepower: 617,
      torque: 553,
      acceleration: 3.8,
      topSpeed: 250,
    },
    powerTrain: {
      engine: "4.4L Twin-Turbocharged V8",
      transmission: "8-speed automatic",
      fuelEconomy: "13 MPG city / 18 MPG highway",
      weight: 5440,
    },
    dimensions: {
      length: 4978,
      width: 2004,
      height: 1745,
      wheelbase: 2975,
    },
    features: {
      driveType: "All-Wheel Drive",
      tireSize: {
        front: "275/40R21",
        rear: "315/35R22",
      },
      battery: "Standard 12V automotive battery",
      fuelTank: 22.5,
    },
  },
];
